select Empno, Empname,deptno, dname from Employee natural join dept;
select Empname,dname,location from Employee natural join dept;
select Empname,dname from Employee natural join dept where job='CLERK';
select e1.Empname as Empname, e1.job as Job, e2.Empname as Manager, e2.job as MgrJob from Employee e1, Employee e2 where e1.managerno=e2.empno;
select Empname from Employee natural join dept where dname='SALES' or dname='RESEARCH';
select Empname,salary from Employee natural join dept where location='BANGALORE';
select Empname,commision from Employee natural join dept where dname='admin' and gender='F';
select Empname from Project inner join workson on Project.proj_num=workson.pno inner join Employee on workson.eno=Employee.empno where pname='Cloud Computing';
select Pname from Project inner join dept on Project.dnum=dept.deptno where dname='admin';
select Empname from Project inner join workson on Project.proj_num=workson.pno inner join Employee on workson.eno=Employee.empno where pname='DBMS' and hours_per_week>20;
select Empname from Employee inner join workson on Employee.empno=workson.eno inner join Project on workson.pno=Project.proj_num where Employee.deptno=Project.dnum;
select Pname from Project inner join dept on Project.dnum=dept.deptno and Project.location=dept.location;
select distinct e2.Empname as ManagerName,Pname from Employee e1 inner join Employee e2 on e1.managerno=e2.empno inner join workson on e2.empno=workson.eno inner join Project on workson.pno=Project.proj_num;
select distinct e2.empname, e2.salary from Employee e1 inner join Employee e2 on e1.managerno=e2.empno inner join workson on e2.empno=workson.eno inner join Project on workson.pno=Project.proj_num where hours_per_week>15 and Pname='Computerization';
select Empname from Employee inner join workson on Employee.empno=workson.eno inner join Project on workson.pno=Project.proj_num where Project.location='MUMBAI';